version: '3'
services:

  worker:
    container_name: worker
    build:
      dockerfile: Containers/coinscoin-base/Dockerfile
      context: .
    entrypoint: []
    command: ["/docker-entrypoint.sh", "worker"]

  worker2:
    container_name: worker2
    build:
      dockerfile: Containers/mssql-python-pyodbc/Dockerfile
      context: .
    entrypoint: []
    command: ["/docker-entrypoint.sh", "justrun"]


  coinscoin-db:
    container_name: coinscoin-db
    ports:
    #  - "127.0.0.1:1433:1433"
      - "1433:1433"
    build:
      dockerfile: Containers/coinscoin-db/Dockerfile
      context: .
    entrypoint: []
    #command: ["/docker-entrypoint.sh", "worker"]

  management:
    build:
      dockerfile: Containers/coinscoin-base/Dockerfile
      context: .
    entrypoint: [ ]
    command: [ "/docker-entrypoint.sh", "justrun"]

  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"

  redis-commander:
    image: rediscommander/redis-commander
    depends_on:
      - redis
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      REDIS_HOSTS: "CoinsCoin:redis:6379"

  monitor:
    build:
      dockerfile: Containers/coinscoin-base/Dockerfile
      context: .
    entrypoint: []
    command: ["flower", "-A", "coinscoin_lib.tasks", "--address=0.0.0.0"]
    ports:
      - "127.0.0.1:5555:5555"


